#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      TARGET:
        default: 'IPQ60XX-WIFI-NO'
        required: true
        type: choice
        options: [IPQ60XX-WIFI-NO, TEST]
      SOURCE:
        default: 'VIKINGYFY/immortalwrt'
        required: true
        type: choice
        options: [VIKINGYFY/immortalwrt, immortalwrt/immortalwrt, LiBwrt-op/openwrt-6.x, qosmio/openwrt-ipq,coolsnowwolf/lede]
      BRANCH:
        default: 'main'
        required: true
        type: string
      SUFFIX:
        default: 'IMM'
        required: true
        type: string
      PACKAGE:
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: true
        required: true
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.TARGET}}
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: TWRT
      #默认WIFI名
      WRT_WIFI: TWRT
      #默认地址
      WRT_IP: 192.168.1.1
      #默认密码，仅作提示，修改无用
      WRT_PW: password|none
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      #后缀名称
      WRT_SUFFIX: ${{matrix.REPO_INFO.SUFFIX}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
